apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    management:
      metrics:
        export:
          wavefront:
            enabled: true
            api-token: ${wavefront-api-token}
            uri: https://vmware.wavefront.com
            source: scdf-k8s
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    imagePullPolicy: Always
        dataflow:
          applicationProperties:
            stream:
              management:
                metrics:
                  export:
                    wavefront:
                      enabled: true
                      api-token: ${wavefront-api-token}
                      uri: https://vmware.wavefront.com
                      source: scdf-k8s
            task:
              management:
                metrics:
                  export:
                    wavefront:
                      enabled: true
                      api-token: ${wavefront-api-token}
                      uri: https://vmware.wavefront.com
                      source: scdf-k8s
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: root
        password: ${mysql-root-password}
        driverClassName: org.mariadb.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"

